const eventsData = [
    {
        id: 1,
        title: 'Tech Innovators Conference 2024',
        location: 'San Francisco, CA',
        date: '2024-12-01',
        time: '9:00 AM - 5:00 PM',
        description: 'Join industry leaders and tech enthusiasts at the Tech Innovators Conference to discuss emerging trends in technology and innovation.',
    },
    {
        id: 2,
        title: 'Finance Meetup 2024',
        location: 'New York, NY',
        date: '2024-11-15',
        time: '6:00 PM - 9:00 PM',
        description: 'Connect with finance professionals and industry experts to explore financial trends, investment strategies, and career growth opportunities.',
    },
    {
        id: 3,
        title: 'Healthcare AI Workshop',
        location: 'Chicago, IL',
        date: '2024-11-20',
        time: '10:00 AM - 4:00 PM',
        description: 'A hands-on workshop on the applications of AI in healthcare, covering topics like data analysis, predictive modeling, and patient care improvement.',
    },
    {
        id: 4,
        title: 'Global Hackathon 2024',
        location: 'Online',
        date: '2024-12-05',
        time: 'Starts at 12:00 PM',
        description: 'Compete with talented developers worldwide in a 48-hour hackathon. Showcase your skills, build innovative projects, and win exciting prizes!',
    },
    {
        id: 5,
        title: 'Women in STEM Summit',
        location: 'Boston, MA',
        date: '2024-11-30',
        time: '9:00 AM - 3:00 PM',
        description: 'A summit dedicated to supporting and empowering women in science, technology, engineering, and mathematics. Network and learn from inspiring leaders.',
    },
    {
        id: 6,
        title: 'Startup Networking Night',
        location: 'Austin, TX',
        date: '2024-11-25',
        time: '5:30 PM - 8:00 PM',
        description: 'An evening for startup founders, investors, and enthusiasts to connect, share insights, and discuss the challenges and rewards of entrepreneurship.',
    },
    {
        id: 7,
        title: 'Cybersecurity Bootcamp',
        location: 'Los Angeles, CA',
        date: '2024-12-10',
        time: '8:00 AM - 5:00 PM',
        description: 'An intensive bootcamp focused on cybersecurity basics, threat analysis, and best practices. Perfect for professionals looking to enhance their skills.',
    },
];

export default eventsData;
